### ISSUE TITLE
nupkg: VERIFICATION.txt is missing from chocolatey packages and malfromed nuspec

### ISSUE THREAD

**Issue by muffins** [osquery/osquery-packaging#16]
In uploading the choco packages, we're failing verification for the `icon` value (it needs to be `iconUrl`, as chocolatey uses an older version of the nuspec that's not consistent with the newer `cpack :((((), as well as including a `[`VERIFICATION.txt`](https://github.com/osquery/osquery/blob/master/tools/deployment/windows_packaging/chocolatey/VERIFICATION.txt)` with our packages. Right now I just performed these actions manually, I'll get a PR up to make this happen automatically asap.

**Comment by Smjert** [comment]
Closing this issue since it has been addressed.
