### ISSUE TITLE
Change to default installation path on RedHat may cause osquery to not work in specific circumstances

### ISSUE THREAD

**Issue by laugmanuel** [osquery/osquery-packaging#17]
I'm not sure, if an issue in this project is the right way to document this, but I do experience problems after the change of the default installation path in https://github.com/osquery/osquery-packaging/pull/13 (and https://github.com/osquery/osquery/issues/7237).

We do use osquery provided in the RPM repo (`https://s3.amazonaws.com/osquery-packages/rpm/<arch>`).
When upgrading to 5.0.x, the binaries get moved to/recreated at `/opt/osquery/bin/` with a symlink in `/usr/local/bin/` (e.g. `/usr/local/bin/osqueryi`) but there is no symlink at the old location `/usr/bin`:
```sh
root@example-dev:/root# osqueryi --version
osqueryi version 5.0.1

root@example-dev:/root# whereis osqueryi
osqueryi: /usr/local/bin/osqueryi

root@example-dev:/root# ls -la /usr/local/bin/osqueryi
lrwxrwxrwx 1 root root 25 Sep  3 05:46 /usr/local/bin/osqueryi -> /opt/osquery/bin/osqueryd

root@example-dev:/root# ls /usr/bin/osqueryi
ls: cannot access '/usr/bin/osqueryi': No such file or directory
```

This causes all tools to fail which use either a hardcoded path to osquery or rely on `PATH` which does not include `/usr/local/bin` by default (e.g. cron).

BTW: When upgrading the package using the package manager (`yum update osquery` on RHEL 7.9 in my case), `osqueryi` is broken until I restart the shell:
```sh
root@example-dev:/root# osqueryi --version
-bash: /bin/osqueryi: No such file or directory

root@example-dev:/root# logout

user@example-dev:/home/user# su -

root@example-dev:/root# osqueryi --version
osqueryi version 5.0.1
```

**Comment by thomas-merz** [comment]
I would also appreciate that the new RPM with version 5 also respects the old paths from previous versions:

Version 4.x
```
$ rpm -qil osquery|grep bin
/usr/bin/osqueryctl
/usr/bin/osqueryd
/usr/bin/osqueryi
```

Version 5 is missing `/usr/bin/` path but is adding `/usr/local/bin` which was never used before 🤔
```
$ rpm -qil osquery|grep bin
/opt/osquery/bin
/opt/osquery/bin/osqueryctl
/opt/osquery/bin/osqueryd
/usr/local/bin
/usr/local/bin/osqueryctl
/usr/local/bin/osqueryi
```

**Comment by directionless** [comment]
`osquery` would probably have been a better repo to open an issue in. The packaging code is split for somewhat mechanical reasons.

TBH I'm somewhat torn, I think 5.0 is a breaking change, and I'd like to eventually only ship things inside `/opt/osquery`. But, these symlinks were there for compatibility, and it sounds like we just got the location wrong. oops. It's probably reasonable for us to ship `/usr` symlinks in the rpm and deb.

@sharvilshah, @Smjert either of you want to weigh in?

**Comment by thomas-merz** [comment]
@directionless , @sharvilshah , @Smjert do you have already an opinion about this?

**Comment by directionless** [comment]
I think we should fix it. PRs welcome, but we'll aim to have it for the 5.1 release.

**Comment by thomas-merz** [comment]
Release 5.1 would be sufficient :-)  
I am really not familiar with the packaging and language used there. But I [added these lines again](https://github.com/osquery/osquery-packaging/pull/13/files#diff-9aa94e89353a736438a066cf779f46be4058f11374ed9a96f4226f191dbaa4a1L25-L27 ) and put it in a [PR](https://github.com/osquery/osquery-packaging/pull/18) 😃
